---
galaxy_info:
  author: Your Name
  description: vLLM server deployment role
  license: MIT
  min_ansible_version: 2.9
  platforms:
    - name: Debian
      versions:
        - bullseye
        - bookworm

  galaxy_tags:
    - vllm
    - llm
    - ai
    - gpu

dependencies: []