---
galaxy_info:
  author: Your Name
  description: Docker Registry deployment role
  license: MIT
  min_ansible_version: 2.9
  platforms:
    - name: Debian
      versions:
        - bullseye
        - bookworm

  galaxy_tags:
    - registry
    - docker

dependencies: []