---
all:
  children:
    registry_servers:
      hosts:
        registry01:
          ansible_host: 192.168.1.101
        registry02:
          ansible_host: 192.168.1.102
    vllm_servers:
      hosts:
        vllm01:
          ansible_host: 192.168.1.201
        vllm02:
          ansible_host: 192.168.1.202
  vars:
    ansible_user: debian
    ansible_ssh_private_key_file: ~/.ssh/id_rsa
    ansible_become: yes
    ansible_become_method: sudo
    ansible_python_interpreter: /usr/bin/python3