FROM nvidia/cuda:12.2.0-devel-ubuntu22.04

# Set the working directory in the container
WORKDIR /

# Install system dependencies
RUN apt-get update && apt-get install -y --no-install-recommends \
    build-essential \
    curl \
    ca-certificates \
    python3.11 \
    python3-pip \
    git \
    && rm -rf /var/lib/apt/lists/*

# Upgrade pip
RUN pip3 install --no-cache-dir --upgrade pip

# install tabbyAPI
RUN git clone https://github.com/theroyallab/tabbyAPI.git
WORKDIR			    /tabbyAPI
COPY config.yml		/tabbyAPI
COPY api_tokens.yml	/tabbyAPI

# Install packages specified in pyproject.toml cu121
RUN pip3 install --no-cache-dir .[cu121]

# Make port 5000 available to the world outside this container
EXPOSE 5000

# Set the entry point
ENTRYPOINT ["python3"]

# Run main.py when the container launches
CMD ["main.py"]
